FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    iputils-ping \
    whois \
    nmap \
  && rm -rf /var/lib/apt/lists/*

COPY requirements/base.txt requirements/base.txt
RUN pip install --no-cache-dir -r requirements/base.txt

COPY . .

RUN mkdir -p /var/log/osint_platform

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
