# Generated by Django 4.2.7 on 2025-09-22 17:12

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("domain", "Domain"),
                            ("ip", "IP Address"),
                            ("email", "Email Address"),
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("phone", "Phone Number"),
                            ("url", "URL"),
                            ("hash", "Hash"),
                            ("file", "File"),
                            ("cryptocurrency", "Cryptocurrency Address"),
                            ("social_media", "Social Media Account"),
                            ("geolocation", "Geolocation"),
                            ("other", "Other"),
                        ],
                        help_text="Type of the entity",
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Primary value of the entity",
                        max_length=500,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable display name",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the entity"),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional properties of the entity",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=1.0, help_text="Confidence score (0.0 to 1.0)"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source where this entity was discovered",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when entity was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when entity was last updated",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags associated with this entity",
                    ),
                ),
                (
                    "is_seed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this entity is a seed entity (starting point)",
                    ),
                ),
            ],
            options={
                "db_table": "entities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("resolves_to", "Resolves To"),
                            ("subdomain_of", "Subdomain Of"),
                            ("hosted_on", "Hosted On"),
                            ("owns", "Owns"),
                            ("associated_with", "Associated With"),
                            ("communicates_with", "Communicates With"),
                            ("located_at", "Located At"),
                            ("member_of", "Member Of"),
                            ("works_for", "Works For"),
                            ("similar_to", "Similar To"),
                            ("linked_to", "Linked To"),
                            ("contains", "Contains"),
                            ("part_of", "Part Of"),
                            ("references", "References"),
                            ("other", "Other"),
                        ],
                        help_text="Type of the relationship",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the relationship"
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional properties of the relationship",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=1.0, help_text="Confidence score (0.0 to 1.0)"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source where this relationship was discovered",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when relationship was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when relationship was last updated",
                    ),
                ),
            ],
            options={
                "db_table": "relationships",
                "ordering": ["-created_at"],
            },
        ),
    ]
