# Generated by Django 4.2.7 on 2025-09-22 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("investigations", "0001_initial"),
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationship",
            name="investigation",
            field=models.ForeignKey(
                help_text="Investigation this relationship belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="investigations.investigation",
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="source_entity",
            field=models.ForeignKey(
                help_text="Source entity of the relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_relationships",
                to="entities.entity",
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="target_entity",
            field=models.ForeignKey(
                help_text="Target entity of the relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_relationships",
                to="entities.entity",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="investigation",
            field=models.ForeignKey(
                help_text="Investigation this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="investigations.investigation",
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(fields=["relationship_type"], name="relationshi_relatio_238db9_idx"),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(fields=["investigation"], name="relationshi_investi_448e37_idx"),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(fields=["source_entity"], name="relationshi_source__702dce_idx"),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(fields=["target_entity"], name="relationshi_target__ca6217_idx"),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(fields=["confidence_score"], name="relationshi_confide_8a025e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="relationship",
            unique_together={("investigation", "source_entity", "target_entity", "relationship_type")},
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["entity_type"], name="entities_entity__d2e80f_idx"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["investigation"], name="entities_investi_88f7c6_idx"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["value"], name="entities_value_52c36f_idx"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["is_seed"], name="entities_is_seed_304507_idx"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["confidence_score"], name="entities_confide_0d0236_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="entity",
            unique_together={("investigation", "entity_type", "value")},
        ),
    ]
