# Generated by Django 4.2.7 on 2025-09-22 17:12

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name of the transform",
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable display name", max_length=255),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of what the transform does"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dns", "DNS"),
                            ("network", "Network"),
                            ("web", "Web"),
                            ("social", "Social Media"),
                            ("search", "Search Engine"),
                            ("threat_intel", "Threat Intelligence"),
                            ("geolocation", "Geolocation"),
                            ("cryptocurrency", "Cryptocurrency"),
                            ("file_analysis", "File Analysis"),
                            ("other", "Other"),
                        ],
                        help_text="Category of the transform",
                        max_length=50,
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("domain", "Domain"),
                            ("ip", "IP Address"),
                            ("email", "Email Address"),
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("phone", "Phone Number"),
                            ("url", "URL"),
                            ("hash", "Hash"),
                            ("file", "File"),
                            ("cryptocurrency", "Cryptocurrency Address"),
                            ("social_media", "Social Media Account"),
                            ("geolocation", "Geolocation"),
                            ("any", "Any Type"),
                        ],
                        help_text="Type of entity this transform accepts as input",
                        max_length=50,
                    ),
                ),
                (
                    "output_types",
                    models.JSONField(
                        default=list,
                        help_text="List of entity types this transform can output",
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(help_text="Name of the underlying OSINT tool", max_length=100),
                ),
                (
                    "command_template",
                    models.TextField(help_text="Command template for executing the tool"),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default parameters for the transform",
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        default=300,
                        help_text="Timeout in seconds for transform execution",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, help_text="Whether this transform is enabled"),
                ),
                (
                    "requires_api_key",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this transform requires an API key",
                    ),
                ),
                (
                    "api_key_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the environment variable for API key",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when transform was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when transform was last updated",
                    ),
                ),
            ],
            options={
                "db_table": "transforms",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["category"], name="transforms_categor_699130_idx"),
                    models.Index(fields=["input_type"], name="transforms_input_t_2e67eb_idx"),
                    models.Index(fields=["is_enabled"], name="transforms_is_enab_84ad44_idx"),
                    models.Index(fields=["tool_name"], name="transforms_tool_na_0161ad_idx"),
                ],
            },
        ),
    ]
