from django.db import migrations


def add_additional_transforms(apps, schema_editor):
    Transform = apps.get_model("transforms", "Transform")

    transforms = [
        {
            "name": "httpx",
            "display_name": "Httpx - HTTP Probing",
            "description": "Probe live HTTP services and normalize reachable URLs",
            "category": "web",
            "input_type": "any",
            "output_types": ["url"],
            "tool_name": "httpx",
            "command_template": "httpx -silent -u {input}",
            "parameters": {"timeout": 120},
            "timeout": 120,
            "is_enabled": True,
            "requires_api_key": False,
            "api_key_name": "",
        },
        {
            "name": "waybackurls",
            "display_name": "Waybackurls - Historical URLs",
            "description": "Fetch historical URLs for a domain from public archives",
            "category": "web",
            "input_type": "any",
            "output_types": ["url"],
            "tool_name": "waybackurls",
            "command_template": "waybackurls {input}",
            "parameters": {"timeout": 120},
            "timeout": 120,
            "is_enabled": True,
            "requires_api_key": False,
            "api_key_name": "",
        },
        {
            "name": "gobuster",
            "display_name": "Gobuster - Directory Enumeration",
            "description": "Enumerate directories and files on a web server using a wordlist",
            "category": "web",
            "input_type": "any",
            "output_types": ["url"],
            "tool_name": "gobuster",
            "command_template": "gobuster dir -u {input} -w /usr/share/wordlists/dirb/common.txt -q",
            "parameters": {"timeout": 300, "mode": "dir", "threads": 30},
            "timeout": 300,
            "is_enabled": True,
            "requires_api_key": False,
            "api_key_name": "",
        },
        {
            "name": "dirb",
            "display_name": "Dirb - Directory Brute Force",
            "description": "Bruteforce directories and files on a web server",
            "category": "web",
            "input_type": "any",
            "output_types": ["url"],
            "tool_name": "dirb",
            "command_template": "dirb {input}",
            "parameters": {"timeout": 300},
            "timeout": 300,
            "is_enabled": True,
            "requires_api_key": False,
            "api_key_name": "",
        },
        {
            "name": "nikto",
            "display_name": "Nikto - Web Server Scan",
            "description": "Scan web servers for common issues and misconfigurations",
            "category": "web",
            "input_type": "any",
            "output_types": ["url", "other"],
            "tool_name": "nikto",
            "command_template": "nikto -h {input}",
            "parameters": {"timeout": 600},
            "timeout": 600,
            "is_enabled": True,
            "requires_api_key": False,
            "api_key_name": "",
        },
        {
            "name": "whatweb",
            "display_name": "WhatWeb - Technology Fingerprinting",
            "description": "Identify web technologies used by a target",
            "category": "web",
            "input_type": "any",
            "output_types": ["url"],
            "tool_name": "whatweb",
            "command_template": "whatweb --log-json=- {input}",
            "parameters": {"timeout": 180},
            "timeout": 180,
            "is_enabled": True,
            "requires_api_key": False,
            "api_key_name": "",
        },
        {
            "name": "wappalyzer",
            "display_name": "Wappalyzer - Technology Fingerprinting",
            "description": "Detect technologies on websites (falls back if CLI not available)",
            "category": "web",
            "input_type": "any",
            "output_types": ["url"],
            "tool_name": "wappalyzer",
            "command_template": "wappalyzer {input}",
            "parameters": {"timeout": 180},
            "timeout": 180,
            "is_enabled": True,
            "requires_api_key": False,
            "api_key_name": "",
        },
        {
            "name": "ping",
            "display_name": "Ping - Reachability Check",
            "description": "Check reachability and extract responding IPs",
            "category": "network",
            "input_type": "any",
            "output_types": ["ip", "other"],
            "tool_name": "ping",
            "command_template": "ping -c 1 {input}",
            "parameters": {"timeout": 30, "count": 1, "wait": 2},
            "timeout": 30,
            "is_enabled": True,
            "requires_api_key": False,
            "api_key_name": "",
        },
        {
            "name": "traceroute",
            "display_name": "Traceroute - Network Path",
            "description": "Trace network path and extract hop IPs",
            "category": "network",
            "input_type": "any",
            "output_types": ["ip"],
            "tool_name": "traceroute",
            "command_template": "traceroute -n {input}",
            "parameters": {"timeout": 120, "max_hops": 30},
            "timeout": 120,
            "is_enabled": True,
            "requires_api_key": False,
            "api_key_name": "",
        },
        {
            "name": "masscan",
            "display_name": "Masscan - Fast Port Scan",
            "description": "Fast port scanning for open services",
            "category": "network",
            "input_type": "any",
            "output_types": ["ip"],
            "tool_name": "masscan",
            "command_template": "masscan {input} -p80,443 --rate 1000",
            "parameters": {"timeout": 300, "ports": "80,443", "rate": 1000},
            "timeout": 300,
            "is_enabled": True,
            "requires_api_key": False,
            "api_key_name": "",
        },
        {
            "name": "zmap",
            "display_name": "ZMap - Internet-wide Scanner",
            "description": "Fast scanning for hosts with a specific open port",
            "category": "network",
            "input_type": "any",
            "output_types": ["ip"],
            "tool_name": "zmap",
            "command_template": "zmap -p 80 -o - {input}",
            "parameters": {"timeout": 300, "port": 80, "rate": 10000},
            "timeout": 300,
            "is_enabled": True,
            "requires_api_key": False,
            "api_key_name": "",
        },
    ]

    for t in transforms:
        name = t.pop("name")
        Transform.objects.get_or_create(name=name, defaults=t)


def remove_additional_transforms(apps, schema_editor):
    Transform = apps.get_model("transforms", "Transform")
    Transform.objects.filter(
        name__in=[
            "httpx",
            "waybackurls",
            "gobuster",
            "dirb",
            "nikto",
            "whatweb",
            "wappalyzer",
            "ping",
            "traceroute",
            "masscan",
            "zmap",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("transforms", "0003_add_recon_transforms"),
    ]

    operations = [
        migrations.RunPython(add_additional_transforms, remove_additional_transforms),
    ]
