# Generated by Django 4.2.7 on 2025-09-22 17:12

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("entities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Investigation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the investigation",
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the investigation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        help_text="Current status of the investigation",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when investigation was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when investigation was last updated",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags associated with this investigation",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the investigation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this investigation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investigations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransformExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transform_name",
                    models.CharField(help_text="Name of the transform being executed", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the execution",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when execution started",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when execution completed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when execution was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when execution was last updated",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parameters passed to the transform",
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Results returned by the transform",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if execution failed"),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for tracking",
                        max_length=255,
                    ),
                ),
                (
                    "input_entity",
                    models.ForeignKey(
                        help_text="Entity that serves as input for the transform",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transform_executions",
                        to="entities.entity",
                    ),
                ),
                (
                    "investigation",
                    models.ForeignKey(
                        help_text="Investigation this execution belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transform_executions",
                        to="investigations.investigation",
                    ),
                ),
            ],
            options={
                "db_table": "transform_executions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="transform_e_status_f39d33_idx"),
                    models.Index(fields=["investigation"], name="transform_e_investi_af75c8_idx"),
                    models.Index(fields=["transform_name"], name="transform_e_transfo_5bf0df_idx"),
                    models.Index(fields=["celery_task_id"], name="transform_e_celery__1f824b_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="investigation",
            index=models.Index(fields=["status"], name="investigati_status_295316_idx"),
        ),
        migrations.AddIndex(
            model_name="investigation",
            index=models.Index(fields=["created_by"], name="investigati_created_3f04ea_idx"),
        ),
        migrations.AddIndex(
            model_name="investigation",
            index=models.Index(fields=["created_at"], name="investigati_created_f9b264_idx"),
        ),
    ]
