# Generated by Django 4.2.7 on 2025-09-22 17:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("analyst", "Analyst"),
                            ("investigator", "Investigator"),
                            ("admin", "Administrator"),
                            ("viewer", "Viewer"),
                        ],
                        default="analyst",
                        help_text="User role in the platform",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization the user belongs to",
                        max_length=255,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="User's phone number", max_length=20
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="User's preferred timezone",
                        max_length=50,
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences and settings",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key for programmatic access",
                        max_length=255,
                    ),
                ),
                (
                    "api_key_created_at",
                    models.DateTimeField(
                        blank=True, help_text="When the API key was created", null=True
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of last login", null=True
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether the user's email is verified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the profile was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the profile was last updated"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["role"], name="user_profil_role_fa03e1_idx"),
                    models.Index(
                        fields=["organization"], name="user_profil_organiz_608b52_idx"
                    ),
                    models.Index(
                        fields=["api_key"], name="user_profil_api_key_fd3e87_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the token", max_length=255
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="The actual token value", max_length=255, unique=True
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("read", "Read Only"),
                            ("write", "Read/Write"),
                            ("admin", "Administrative"),
                        ],
                        default="read",
                        help_text="Scope of permissions for this token",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the token is active"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the token expires (null = never)",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="When the token was last used", null=True
                    ),
                ),
                (
                    "last_used_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address where token was last used",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the token was created"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="api_tokens_token_8d7e16_idx"),
                    models.Index(fields=["user"], name="api_tokens_user_id_caf836_idx"),
                    models.Index(
                        fields=["is_active"], name="api_tokens_is_acti_949075_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="api_tokens_expires_a047d2_idx"
                    ),
                ],
            },
        ),
    ]
